[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:edge"

[target.x86_64-linux-android]
image = "ghcr.io/cross-rs/x86_64-linux-android:edge"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:edge"

[target.x86_64-unknown-freebsd]
image = "ghcr.io/cross-rs/x86_64-unknown-freebsd:edge"

[target.x86_64-unknown-netbsd]
image = "ghcr.io/cross-rs/x86_64-unknown-netbsd:edge"

[target.wasm32-unknown-emscripten]
image = "ghcr.io/cross-rs/wasm32-unknown-emscripten:edge"

